spring:
  application:
    name: gateway-server

  config:
    import:
      - configserver:${CONFIG_SERVER:http://config-server:8888}
      - vault://

  cloud:
    config:
      enabled: true
      fail-fast: true
      username: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin}

    vault:
      enabled: true
      uri: ${VAULT:http://vault:8200}
      authentication: token
      token: ${VAULT_TOKEN}
