spring:
  application:
    name: product-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  config:
    import:
      - configserver:${CONFIG_SERVER:http://config-server:8888}
      - vault://

  cloud:
    config:
      enabled: true
      fail-fast: true
      username: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin}

    vault:
      enabled: true
      uri: ${VAULT:http://vault:8200}
      authentication: token
      token: ${VAULT_TOKEN}

springdoc:
  title: "Product Api"
  description: "Api for product"
  version: "v1.0.0"
  contact-name: "Gibbsson Farias Castillo"
  contact-email: "gibbfarc17@gmail.com"
  contact-url: "https://github.com/gibbssonfarias30"

  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html