server:
  port: 8001
  servlet:
    context-path: /api/v1

spring:
  application:
    name: product-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-product
    username: sa
    password: ''

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true

springdoc:
  title: "Product Api"
  description: "Api for product"
  version: "v1.0.0"
  contact-name: "Gibbsson Farias Castillo"
  contact-email: "gibbfarc17@gmail.com"
  contact-url: "https://github.com/gibbssonfarias30"

  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
